version: '3.8'

services:
  emurom:
    image: emurom
    container_name: emurom_container
    ports:
      - "3000:3000"
    volumes:
      - "C:/Users/invalid/Documents/GitHub/EmuRom/data:/app/data"
    restart: unless-stopped
